/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { X, Shield, FileText, HelpCircle } from 'lucide-react';
import { useLanguage } from '../lib/LanguageContext';

interface InfoModalProps {
  isOpen: boolean;
  type: 'privacy' | 'terms' | 'support' | null;
  onClose: () => void;
}

export default function InfoModal({ isOpen, type, onClose }: InfoModalProps) {
  const { t, language } = useLanguage();

  if (!isOpen || !type) return null;

  const content = {
    en: {
      privacy: {
        title: 'Privacy Policy',
        icon: <Shield className="w-6 h-6 text-peloka-primary" />,
        paragraphs: [
          'At Peloka Decision, we value your trust and prioritize your absolute confidentiality. Your decision-making process is your own business.',
          'No Data Collection: We do not collect, harvest, monitor, or transmit any data you enter into this application. All options, ranges, list items, synaptic weights, and outcomes are processed entirely inside your local web browser sandbox.',
          'Local Storage Only: Your language settings are saved on your own device using local storage purely to remember your preferences for your next visit. We have no backend databases, analytical tracking, or remote log registers.',
          'Zero Cookies: We do not set tracking cookies or connect to third-party ad networks. You are completely anonymous. No servers are contacted, guaranteeing absolute, high-integrity random results.'
        ]
      },
      terms: {
        title: 'Terms of Service',
        icon: <FileText className="w-6 h-6 text-peloka-primary" />,
        paragraphs: [
          'Welcome to the Peloka Decision Engine. By accessing and using this web application, you acknowledge and agree to the following conditions:',
          'Informational & Entertainment Purpose: The outcomes generated by the randomizer core are mathematically randomized. They represent high-precision statistical choices and should be used responsibly. They do not constitute professional, legal, medical, or financial advice.',
          'No Warranties: The application is provided "as is" without warranties of any kind. We are not liable for any actions taken or decisions made based on the results generated by our synaptic systems.',
          'Permitted Use: You are free to use this system for personal, industrial, or educational decision-making. No license is required.'
        ]
      },
      support: {
        title: 'Support Desk',
        icon: <HelpCircle className="w-6 h-6 text-peloka-primary" />,
        paragraphs: [
          'Need help calibrating your decision matrix? Our support channels are open.',
          'Self-Hosted Sandbox: Because our core decision-engine runs 100% on-device inside your browser client, typical data synchronization issues do not exist. If the system behaves unexpectedly, simply click "Flush Buffer" or reload your page to reset the local memory registers.',
          'Contact: For any inquiries, feature requests, or enterprise integrations, please reach out directly via support@peloka.com or through our verified developer hubs.'
        ]
      }
    },
    tr: {
      privacy: {
        title: 'Gizlilik Politikası',
        icon: <Shield className="w-6 h-6 text-peloka-primary" />,
        paragraphs: [
          'Peloka Decision olarak, güveninize değer veriyor ve mutlak gizliliğinizi her şeyin üzerinde tutuyoruz. Karar verme süreciniz tamamen size aittir.',
          'Veri Toplama Yok: Bu uygulamaya girdiğiniz hiçbir veriyi toplamıyoruz, işlemiyoruz, izlemiyoruz veya aktarmıyoruz. Tüm seçenekler, aralıklar, liste öğeleri, sinaptik ağırlıklar ve üretilen sonuçlar tamamen yerel tarayıcınızın güvenli ortamında işlenir.',
          'Yalnızca Yerel Depolama: Dil ayarlarınız, bir sonraki ziyaretinizde tercihlerinizi hatırlamak amacıyla yerel depolama (localStorage) kullanılarak yalnızca kendi cihazınızda saklanır. Herhangi bir arka uç veritabanımız, analitik takip sistemimiz veya uzak günlük kaydımız bulunmamaktadır.',
          'Sıfır Çerez: Takip çerezleri kullanmıyoruz veya üçüncü taraf reklam ağlarına bağlanmıyoruz. Tamamen anonimsiniz. Sunucularla hiçbir veri alışverişi yapılmaz, bu da mutlak ve yüksek bütünlüklü rastgele sonuçları garanti eder.'
        ]
      },
      terms: {
        title: 'Kullanım Koşulları',
        icon: <FileText className="w-6 h-6 text-peloka-primary" />,
        paragraphs: [
          'Peloka Karar Motoru\'na hoş geldiniz. Bu web uygulamasını kullanarak aşağıdaki koşulları kabul etmiş sayılırsınız:',
          'Bilgi ve Eğlence Amaçlı Kullanım: Karar motoru tarafından üretilen sonuçlar matematiksel olarak rastgeleleştirilmiştir. Bunlar yüksek hassasiyetli istatistiksel seçimleri temsil eder ve sorumlu bir şekilde kullanılmalıdır. Profesyonel, hukuki, tıbbi veya finansal tavsiye niteliği taşımazlar.',
          'Garanti Yoktur: Bu uygulama, olduğu gibi sunulmaktadır ve hiçbir garanti vermemektedir. Sinaptik sistemlerimizin ürettiği sonuçlara dayanarak alınan kararlardan veya yapılan işlemlerden hiçbir sorumluluk kabul edilmez.',
          'İzin Verilen Kullanım: Bu sistemi kişisel, endüstriyel veya eğitim amaçlı karar verme süreçlerinizde özgürce kullanabilirsiniz. Herhangi bir lisans ücreti gerekmemektedir.'
        ]
      },
      support: {
        title: 'Destek Masası',
        icon: <HelpCircle className="w-6 h-6 text-peloka-primary" />,
        paragraphs: [
          'Karar matrisinizi kalibre etmekte yardıma mı ihtiyacınız var? Destek kanallarımız her zaman açık.',
          'Yerel Güvenli Alan (Sandbox): Karar motorumuz %100 kendi tarayıcı istemcinizin içinde çalıştığı için, genel senkronizasyon veya veri tabanı sorunları yaşanmaz. Sistem beklenmedik şekilde davranırsa, bellek kütüğünü sıfırlamak için "Belleği Boşalt" butonuna tıklamanız veya sayfayı yenilemeniz yeterlidir.',
          'İletişim: Sorularınız, özellik talepleriniz veya kurumsal entegrasyonlar için lütfen support@peloka.com adresi üzerinden bizimle iletişime geçin.'
        ]
      }
    }
  };

  const currentContent = (content[language] || content['en'])[type];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 animate-fade-in select-none">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-peloka-bg-dark/80 backdrop-blur-md transition-opacity cursor-pointer"
        onClick={onClose}
      />

      {/* Modal Container */}
      <div className="relative w-full max-w-lg bg-peloka-surface border border-peloka-surface-high/80 rounded-2xl p-6 md:p-8 shadow-2xl z-10 animate-scale-in">
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-peloka-primary/40 to-transparent" />

        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1.5 rounded-lg text-peloka-on-surface-variant hover:text-peloka-primary hover:bg-peloka-bg-dark/40 transition-all cursor-pointer"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Title */}
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2.5 rounded-xl bg-peloka-primary/10 border border-peloka-primary/20">
            {currentContent.icon}
          </div>
          <h2 className="font-display font-bold text-xl md:text-2xl text-peloka-on-surface">
            {currentContent.title}
          </h2>
        </div>

        {/* Content Paragraphs */}
        <div className="flex flex-col gap-4 text-sm text-peloka-on-surface-variant leading-relaxed max-h-[350px] overflow-y-auto pr-2">
          {currentContent.paragraphs.map((p, idx) => (
            <p key={idx} className="font-sans">
              {p}
            </p>
          ))}
        </div>

        {/* Footer actions */}
        <div className="mt-8 pt-4 border-t border-peloka-surface-high/40 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl text-xs font-semibold uppercase tracking-wider text-peloka-on-primary bg-peloka-primary hover:brightness-110 active:scale-95 transition-all cursor-pointer"
          >
            {language === 'tr' ? 'Kapat' : 'Close'}
          </button>
        </div>
      </div>
    </div>
  );
}
